### ISSUE TITLE
RecordNotFound Error when trying to click recommended service

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/marketplace#1897] opened 2021-03-19 14:23 UTC
**Describe the bug**
MP returns an `ActiveRecord::RecordNotFound` error when trying to click a recommended service *while* filtering by *any* category.

**To Reproduce**
1. Go to `/services`
2. Click on *any* catgory filter
3. Click a recommended service (doesn't matter if the service is recommended by recommender system or SimpleRecommender) in the recommended box
4. See `ActiveRecord::RecordNotFound`

**Expected behavior**
See clicked recommended service.

**Screenshots**
![image](https://user-images.githubusercontent.com/30239467/111794976-12c98c00-88c7-11eb-8c5a-761d008fa943.png)

**Comment by bwilk** [comment] 2021-03-19 14:27
@wujuu take a look at the URL - this is the routing problem

**Comment by JanKapala** [comment] 2021-03-25 18:32
I've tried to reproduce this bug after #1866 has been merged (that PR claimed to solve this bug), but it wasn't possible due to no recommendation panel displaying at all if some category (doesn't matter which exactly) is clicked (if `All resources` are clicked recommendation panel is displayed properly) - so this is another bug that masks the previous one.

I recommend not to close this issue. Moreover I've opened a new one (referencing this new bug) here:

**Comment by JanKapala** [comment] 2021-03-25 18:42
I confirm that this bug is fixed in merged #1866

**Comment by JanKapala** [comment] 2021-03-25 18:43
issue can be closed

**Closed** 2024-02-16 14:48 UTC
Labels: bug, recommender
