### ISSUE TITLE
search bar not working in the category 

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#356] opened 2018-11-12 22:40 UTC
i'm in thematic services category lloking for opencoasts (part of a category)

i insert opencoast to the search bar and there is nothing

EDIT: Search bar is working, but it searches inside selected category. #376 takes care of that.

**Comment by roksanaer** [comment] 2018-11-13 09:12
as discussed - we need to allow user to set the scope of the search: category or global

**Comment by michal-szostak** [comment] 2018-11-13 14:32
Closing as "Not a Bug"

**Closed** 2018-11-13 14:31 UTC
Labels: bug
