### ISSUE TITLE
Recommender System doesn't recieve proper category filter field

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/marketplace#1898] opened 2021-03-19 14:45 UTC
**Description**
When filtering by category that isn't a node category in the ancestry category tree structure, `category_id` search_data field is only that category. We also need to add all of the child categories, similiar to how it is done with `scientific_domains`. Also requires a minor change in recommender system `recommendations` schema (`category_id`(`fields.Integer()`) to `categories`(`fields.List(fields.Integer)`)

**Steps to Reproduce**
1. Go to `\service`
2. Click on any supercategory (like `Access physical & eInfrastructures`)
3. See this json sent to `RECOMMENDER_HOST\recommendations` endpoint:
`[...]'search_data': {'category_id': 11, 'sort': '_score'} [...]`

**What is expected?**
See this json sent to `RECOMMENDER_HOST\recommendations` endpoint:
`[...] 'search_data': {"categories":[11,23,25,27,30,3,35,39,47,52,53,55,57,59,68,70,72,74,80,83,84,85,88,92,96,97,98,106,115,117,124,127,128,130,131,133,148,151,153,154,161,163,168,170,171,175,177,179,180,181,182,189,194,200,201,203],"sort":"_score"} [...]`

**Additional context**
I suggest using `Category.find(:id).descendant_ids`

**Comment by danielkryska** [comment] 2021-03-23 09:14
Proper category_id is available on https://github.com/cyfronet-fid/marketplace/issues/1865 ... It's not a bug, it's a feature related to API changes.

**Comment by danielkryska** [comment] 2021-03-23 09:15
Reference view

![111321238-07c4f080-8668-11eb-8e9c-1e5fe1512f9f](https://user-images.githubusercontent.com/31220811/112122531-aac5bf00-8bc0-11eb-8d8b-93d477866025.png)

**Comment by JanKapala** [comment] 2021-03-25 18:05
> Proper category_id is available on #1865 ... It's not a bug, it's a feature related to API changes.

@danielkryska, it is bug and I've updated it on the recommender side here: https://github.com/cyfronet-fid/recommender-system/pull/42

Please, update it on the marketplace side too.

This is what this part of the API looked like before:
![old_part_of_the_api](https://user-images.githubusercontent.com/16139477/112521355-b372ec80-8d9c-11eb-9ac2-b67178c56f73.png)

And this is what it looks like now:
![updated_part_of_the_api](https://user-images.githubusercontent.com/16139477/112521062-5e36db00-8d9c-11eb-8831-3ea43e1ae6db.jpg)

**Comment by JanKapala** [comment] 2021-03-26 08:37
I've created new issue here: #1927

**Comment by michal-szostak** [comment] 2022-01-12 13:28
Is this issue still valid? @wujuu @Michal-Kolomanski @JanKapala ?

**Comment by Michal-Kolomanski** [comment] 2022-01-13 12:42
@michal-szostak unfortunately, it is still valid. It is strongly connected to #2226 #2495 and even there is [PR](https://github.com/cyfronet-fid/marketplace/pull/2227) which was not merged.

**Comment by Michal-Kolomanski** [comment] 2022-02-07 08:40
Is not an issue anymore

**Closed by Michal-Kolomanski** 2022-02-07 08:40 UTC
Labels: enhancement, recommender
